name: dbt
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - pip=20.3
  - numpy=1.22.3
  - cudatoolkit=11.3
  - pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torch==1.12.0+cu113
    - torchvision==0.13.0+cu113
    - diffusers
    - accelerate
    - tensorboard
    - transformers
    - ftfy
    - triton
    - https://github.com/TheLastBen/fast-stable-diffusion/raw/main/precompiled/A100/xformers-0.0.13.dev0-py3-none-any.whl