accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1"  \
  --instance_data_dir="./inputs" \
  --output_dir="./dbmodel" \
  --instance_prompt="<cat-toy> toy" \
  --resolution=768 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=300 \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --num_class_images=200